// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetFormation_APIS.Data;

#nullable disable

namespace PetFormation_APIS.Migrations
{
    [DbContext(typeof(PetFormationDbContext))]
    partial class PetFormationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PetFormation_APIS.Models.Cliente", b =>
                {
                    b.Property<string>("CEDULA_CLIENTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CORREO_CLIENTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIRECCION_CLIENTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_CLIENTE")
                        .HasColumnType("int");

                    b.Property<string>("NOMBRE_CLIENTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELEFONO_CLIENTE")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
